# Generated by Django 5.2
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('accounts', '0002_alter_user_managers')]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_icon',
            field=models.FileField(blank=True, null=True, upload_to='profile_icons/'),
        ),
    ]
